eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
 
 
 

management:
  tracing:
    sampling:
      probability: 1.0
  
  #zipkin:
   # tracing:
    #  endpoint: http://localhost:9411/api/v2/spans  
        
  endpoints:
    web:
      exposure:
        include: refresh, health, info, prometheus
  
  endpoint:
    health:
      show-details: always
      
  metrics:
    tags:
      application: ${spring.application.name}          
   
   

#server:
 #address: 0.0.0.0
 

jwt:
 access:
  secret: MysuperSecretKeyForJWT1234567890098765432dffgdfsgfgsfgsdfgfsfgffgsfg456w5w465w4rggfg4453
  expiration: 9000   # 15 min +
 refresh:
  secret: MysuperSecretKeyForJWT123456789009876hd7532dffgdfsgfgsfgsdfgfsfgffgsfg456w5w465w4rggfg4453
  expiration: 604800  # 7 days
 roles:
 admin: ROLE_ADMIN
 user: ROLE_USER
 

    
    
