eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
 
 

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info
        

jwt:
 access:
  secret: MysuperSecretKeyForJWT1234567890098765432dffgdfsgfgsfgsdfgfsfgffgsfg456w5w465w4rggfg4453
  expiration: 900   # 15 min
 refresh:
  secret: MysuperSecretKeyForJWT123456789009876hd7532dffgdfsgfgsfgsdfgfsfgffgsfg456w5w465w4rggfg4453
  expiration: 604800  # 7 days
 roles:
 admin: ROLE_ADMIN
 user: ROLE_USER
 
 spring:
  kafka:
   bootstrap-servers: localhost:9092
  cloud:
   config:
    override-none: true


app:
  kafka:
    topic: orders-topic2
    
    
